### ISSUE TITLE
RuntimeError: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

### ISSUE THREAD

**Issue by monajalal** [shanice-l/gdrnpp_bop2022#101]
I tried the inference on lmo and still get same error

```

(gdrnpp) mona@ada:~/gdrnpp_bop2022$ ./core/gdrn_modeling/test_gdrn.sh ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py 0 ./output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/model_final_wo_optim.pth



objects      mssd_0.050:0.500
ape          72.00
can          83.92
cat          66.67
driller      88.00
duck         53.50
eggbox       29.83
glue         68.43
holepuncher  65.80
Avg(8)       66.46
  0%|          | 0/1 [00:00<?, ?it/s]
20240103_113838|WRN|core.gdrn_modeling.engine.test_utils@422: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.
20240103_113838|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (75815), thread 'MainThread' (140686502927232):
Traceback (most recent call last):

> File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', re...
    └ <function main at 0x7ff2e1cce4d0>

  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 205, in main
    ).run(args, cfg)
          │     └ Config (path: ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_RO...
          └ Namespace(config_file='./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', re...

  File "/home/mona/.local/lib/python3.10/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', r...
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7ff2e1d11b40>>, <bound m...
  File "/home/mona/.local/lib/python3.10/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py', r...
           └ <bound method Lite.run of <__main__.Lite object at 0x7ff2e1d11b40>>

  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 183, in run
    return self.do_test(cfg, model)
           │    │       │    └ _LiteModule(
           │    │       │        (_module): GDRN_DoubleMask(
           │    │       │          (backbone): FeatureListNet(
           │    │       │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
           │    │       └ Config (path: ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_RO...
           │    └ <function GDRN_Lite.do_test at 0x7ff2e8f54c10>
           └ <__main__.Lite object at 0x7ff2e1d11b40>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 159, in do_test
    results_i = gdrn_inference_on_dataset(cfg, model, data_loader, evaluator, amp_test=cfg.TEST.AMP_TEST)
                │                         │    │      │            │                   └ Config (path: ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_RO...
                │                         │    │      │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>
                │                         │    │      └ <pytorch_lightning.lite.wrappers._LiteDataLoader object at 0x7ff2e1912860>
                │                         │    └ _LiteModule(
                │                         │        (_module): GDRN_DoubleMask(
                │                         │          (backbone): FeatureListNet(
                │                         │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
                │                         └ Config (path: ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_RO...
                └ <function gdrn_inference_on_dataset at 0x7ff2e8f0e7a0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 804, in gdrn_inference_on_dataset
    results = evaluator.evaluate()  # results is always None
              │         └ <function GDRN_Evaluator.evaluate at 0x7ff2e8f0f760>
              └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 584, in evaluate
    return self._eval_predictions()
           │    └ <function GDRN_Evaluator._eval_predictions at 0x7ff2e8f0f7f0>
           └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 595, in _eval_predictions
    save_and_eval_results(self.cfg, results_all, self._output_dir, obj_ids=self.obj_ids)
    │                     │    │    │            │    │                    │    └ [1, 5, 6, 8, 9, 10, 11, 12]
    │                     │    │    │            │    │                    └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>
    │                     │    │    │            │    └ 'output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/l...
    │                     │    │    │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>
    │                     │    │    └ {'iter0': [{'scene_id': '2', 'im_id': 3, 'obj_id': 1, 'score': tensor(0.0522, dtype=torch.float64), 'R': [-0.2535116374492645...
    │                     │    └ Config (path: ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py): {'OUTPUT_RO...
    │                     └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7ff2e1d107f0>
    └ <function save_and_eval_results at 0x7ff2e8f0eb90>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 73, in save_and_eval_results
    load_and_print_val_scores_tab(
    └ <function load_and_print_val_scores_tab at 0x7ff2e8f0f1c0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 423, in load_and_print_val_scores_tab
    raise RuntimeError("{} does not exist.".format(score_root))
                                                   └ 'output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/l...

RuntimeError: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test/error:vsd_ntop:1_delta:15.000_tau:0.050 does not exist.

```

I have these files:

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ tree output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test
output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test
├── error:ad_ntop:1
│   ├── errors_000002.json
│   ├── matches_th:0.020_min-visib:-1.000.json
│   ├── matches_th:0.050_min-visib:-1.000.json
│   ├── matches_th:0.100_min-visib:-1.000.json
│   ├── scores_th:0.020_min-visib:-1.000.json
│   ├── scores_th:0.050_min-visib:-1.000.json
│   └── scores_th:0.100_min-visib:-1.000.json
├── error:mspd_ntop:1
│   ├── errors_000002.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:15.000_min-visib:-1.000.json
│   ├── matches_th:20.000_min-visib:-1.000.json
│   ├── matches_th:25.000_min-visib:-1.000.json
│   ├── matches_th:30.000_min-visib:-1.000.json
│   ├── matches_th:35.000_min-visib:-1.000.json
│   ├── matches_th:40.000_min-visib:-1.000.json
│   ├── matches_th:45.000_min-visib:-1.000.json
│   ├── matches_th:50.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:15.000_min-visib:-1.000.json
│   ├── scores_th:20.000_min-visib:-1.000.json
│   ├── scores_th:25.000_min-visib:-1.000.json
│   ├── scores_th:30.000_min-visib:-1.000.json
│   ├── scores_th:35.000_min-visib:-1.000.json
│   ├── scores_th:40.000_min-visib:-1.000.json
│   ├── scores_th:45.000_min-visib:-1.000.json
│   ├── scores_th:50.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
├── error:mssd_ntop:1
│   ├── errors_000002.json
│   ├── matches_th:0.050_min-visib:-1.000.json
│   ├── matches_th:0.100_min-visib:-1.000.json
│   ├── matches_th:0.150_min-visib:-1.000.json
│   ├── matches_th:0.200_min-visib:-1.000.json
│   ├── matches_th:0.250_min-visib:-1.000.json
│   ├── matches_th:0.300_min-visib:-1.000.json
│   ├── matches_th:0.350_min-visib:-1.000.json
│   ├── matches_th:0.400_min-visib:-1.000.json
│   ├── matches_th:0.450_min-visib:-1.000.json
│   ├── matches_th:0.500_min-visib:-1.000.json
│   ├── scores_th:0.050_min-visib:-1.000.json
│   ├── scores_th:0.100_min-visib:-1.000.json
│   ├── scores_th:0.150_min-visib:-1.000.json
│   ├── scores_th:0.200_min-visib:-1.000.json
│   ├── scores_th:0.250_min-visib:-1.000.json
│   ├── scores_th:0.300_min-visib:-1.000.json
│   ├── scores_th:0.350_min-visib:-1.000.json
│   ├── scores_th:0.400_min-visib:-1.000.json
│   ├── scores_th:0.450_min-visib:-1.000.json
│   └── scores_th:0.500_min-visib:-1.000.json
├── error:reS_ntop:1
│   ├── errors_000002.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:2.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:2.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
├── error:teS_ntop:1
│   ├── errors_000002.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:2.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:2.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
└── log.log

5 directories, 64 files

```

**Comment by monajalal** [comment]
I had missed to install bop_renderer dependency. 

after doing so, it worked with no error and ending in results such as below:

```
objects      reS_2  reS_5  reS_10
ape          12.57  63.43  88.00
can          40.70  79.90  95.98
cat          14.04  45.03  78.36
driller      50.50  83.00  97.50
duck         9.44   29.44  71.67
eggbox       0.56   18.89  65.00
glue         10.71  35.71  74.29
holepuncher  26.50  65.00  94.00
Avg(8)       20.63  52.55  83.10
20240103_135803|core.gdrn_modeling.engine.test_utils@411: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test *********************
20240103_135803|core.gdrn_modeling.engine.test_utils@417: 
objects      teS_2  teS_5  teS_10
ape          81.14  95.43  96.57
can          83.42  95.48  99.50
cat          60.23  86.55  93.57
driller      77.50  96.50  99.00
duck         53.33  95.56  98.89
eggbox       10.00  43.33  69.44
glue         55.71  85.71  95.00
holepuncher  42.50  95.50  98.00
Avg(8)       57.98  86.76  93.75
20240103_135803|core.gdrn_modeling.engine.test_utils@428: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test *********************
20240103_135803|core.gdrn_modeling.engine.test_utils@453: 
objects      mspd_5:50  mssd_0.050:0.500  vsd_0.050:0.500  ad_0.020  ad_0.050  ad_0.100  reS_2  reS_5  reS_10  teS_2  teS_5  teS_10
ape          91.71      72.00             51.50            0.57      14.29     49.71     12.57  63.43  88.00   81.14  95.43  96.57
can          93.77      83.92             69.23            3.52      38.69     83.42     40.70  79.90  95.98   83.42  95.48  99.50
cat          91.75      66.67             51.56            1.17      16.96     50.29     14.04  45.03  78.36   60.23  86.55  93.57
driller      91.25      88.00             73.49            6.00      52.50     85.50     50.50  83.00  97.50   77.50  96.50  99.00
duck         90.89      53.50             49.59            0.00      2.22      8.33      9.44   29.44  71.67   53.33  95.56  98.89
eggbox       63.56      29.83             17.85            1.11      8.33      33.89     0.56   18.89  65.00   10.00  43.33  69.44
glue         86.00      68.43             49.68            10.71     55.71     76.43     10.71  35.71  74.29   55.71  85.71  95.00
holepuncher  89.75      65.80             46.85            0.50      5.50      25.50     26.50  65.00  94.00   42.50  95.50  98.00
Avg(8)       87.50      66.46             51.74            2.95      24.28     51.63     20.63  52.55  83.10   57.98  86.76  93.75
20240103_135803|core.gdrn_modeling.engine.test_utils@453: 
objects           ape    can    cat    driller  duck   eggbox  glue   holepuncher  Avg(8)
mspd_5:50         91.71  93.77  91.75  91.25    90.89  63.56   86.00  89.75        87.50
mssd_0.050:0.500  72.00  83.92  66.67  88.00    53.50  29.83   68.43  65.80        66.46
vsd_0.050:0.500   51.50  69.23  51.56  73.49    49.59  17.85   49.68  46.85        51.74
ad_0.020          0.57   3.52   1.17   6.00     0.00   1.11    10.71  0.50         2.95
ad_0.050          14.29  38.69  16.96  52.50    2.22   8.33    55.71  5.50         24.28
ad_0.100          49.71  83.42  50.29  85.50    8.33   33.89   76.43  25.50        51.63
reS_2             12.57  40.70  14.04  50.50    9.44   0.56    10.71  26.50        20.63
reS_5             63.43  79.90  45.03  83.00    29.44  18.89   35.71  65.00        52.55
reS_10            88.00  95.98  78.36  97.50    71.67  65.00   74.29  94.00        83.10
teS_2             81.14  83.42  60.23  77.50    53.33  10.00   55.71  42.50        57.98
teS_5             95.43  95.48  86.55  96.50    95.56  43.33   85.71  95.50        86.76
teS_10            96.57  99.50  93.57  99.00    98.89  69.44   95.00  98.00        93.75
100%|##########| 1/1 [00:00<00:00, 37.64it/s]
20240103_135803|core.gdrn_modeling.engine.test_utils@456: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test
20240103_135803|core.gdrn_modeling.engine.test_utils@80: eval time: 294.73648615299317s

```

**Comment by tsrobcvai** [comment]
> I had missed to install bop_renderer dependency.
> 
> after doing so, it worked with no error and ending in results such as below:
> 
> ```
> objects      reS_2  reS_5  reS_10
> ape          12.57  63.43  88.00
> can          40.70  79.90  95.98
> cat          14.04  45.03  78.36
> driller      50.50  83.00  97.50
> duck         9.44   29.44  71.67
> eggbox       0.56   18.89  65.00
> glue         10.71  35.71  74.29
> holepuncher  26.50  65.00  94.00
> Avg(8)       20.63  52.55  83.10
> 20240103_135803|core.gdrn_modeling.engine.test_utils@411: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test *********************
> 20240103_135803|core.gdrn_modeling.engine.test_utils@417: 
> objects      teS_2  teS_5  teS_10
> ape          81.14  95.43  96.57
> can          83.42  95.48  99.50
> cat          60.23  86.55  93.57
> driller      77.50  96.50  99.00
> duck         53.33  95.56  98.89
> eggbox       10.00  43.33  69.44
> glue         55.71  85.71  95.00
> holepuncher  42.50  95.50  98.00
> Avg(8)       57.98  86.76  93.75
> 20240103_135803|core.gdrn_modeling.engine.test_utils@428: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-lmo-test-iter0_lmo-test *********************
> 20240103_135803|core.gdrn_modeling.engine.test_utils@453: 
> objects      mspd_5:50  mssd_0.050:0.500  vsd_0.050:0.500  ad_0.020  ad_0.050  ad_0.100  reS_2  reS_5  reS_10  teS_2  teS_5  teS_10
> ape          91.71      72.00             51.50            0.57      14.29     49.71     12.57  63.43  88.00   81.14  95.43  96.57
> can          93.77      83.92             69.23            3.52      38.69     83.42     40.70  79.90  95.98   83.42  95.48  99.50
> cat          91.75      66.67             51.56            1.17      16.96     50.29     14.04  45.03  78.36   60.23  86.55  93.57
> driller      91.25      88.00             73.49            6.00      52.50     85.50     50.50  83.00  97.50   77.50  96.50  99.00
> duck         90.89      53.50             49.59            0.00      2.22      8.33      9.44   29.44  71.67   53.33  95.56  98.89
> eggbox       63.56      29.83             17.85            1.11      8.33      33.89     0.56   18.89  65.00   10.00  43.33  69.44
> glue         86.00      68.43             49.68            10.71     55.71     76.43     10.71  35.71  74.29   55.71  85.71  95.00
> holepuncher  89.75      65.80             46.85            0.50      5.50      25.50     26.50  65.00  94.00   42.50  95.50  98.00
> Avg(8)       87.50      66.46             51.74            2.95      24.28     51.63     20.63  52.55  83.10   57.98  86.76  93.75
> 20240103_135803|core.gdrn_modeling.engine.test_utils@453: 
> objects           ape    can    cat    driller  duck   eggbox  glue   holepuncher  Avg(8)
> mspd_5:50         91.71  93.77  91.75  91.25    90.89  63.56   86.00  89.75        87.50
> mssd_0.050:0.500  72.00  83.92  66.67  88.00    53.50  29.83   68.43  65.80        66.46
> vsd_0.050:0.500   51.50  69.23  51.56  73.49    49.59  17.85   49.68  46.85        51.74
> ad_0.020          0.57   3.52   1.17   6.00     0.00   1.11    10.71  0.50         2.95
> ad_0.050          14.29  38.69  16.96  52.50    2.22   8.33    55.71  5.50         24.28
> ad_0.100          49.71  83.42  50.29  85.50    8.33   33.89   76.43  25.50        51.63
> reS_2             12.57  40.70  14.04  50.50    9.44   0.56    10.71  26.50        20.63
> reS_5             63.43  79.90  45.03  83.00    29.44  18.89   35.71  65.00        52.55
> reS_10            88.00  95.98  78.36  97.50    71.67  65.00   74.29  94.00        83.10
> teS_2             81.14  83.42  60.23  77.50    53.33  10.00   55.71  42.50        57.98
> teS_5             95.43  95.48  86.55  96.50    95.56  43.33   85.71  95.50        86.76
> teS_10            96.57  99.50  93.57  99.00    98.89  69.44   95.00  98.00        93.75
> 100%|##########| 1/1 [00:00<00:00, 37.64it/s]
> 20240103_135803|core.gdrn_modeling.engine.test_utils@456: output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/inference_model_final_wo_optim/lmo_bop_test
> 20240103_135803|core.gdrn_modeling.engine.test_utils@80: eval time: 294.73648615299317s
> ```
Hi, I met the same issue, but it cannot be solved after installing bop_renderer. Could you give me more details?

**Comment by Sar-thak-3** [comment]
Hi, @monajalal @tsrobcvai I am also encountering the same issue,
Command `import bop_renderer` is working for me but this error still persists, would you kindly help me resolving the error!

**Comment by 1230678** [comment]
我也遇到了同样的问题，请问你们解决了吗
