### ISSUE TITLE
visualizing results of inference on lmo -- FileNotFoundError: [Errno 2] No such file or directory: 'output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl'

### ISSUE THREAD

**Issue by monajalal** [shanice-l/gdrnpp_bop2022#102]
After finishing the inference on lmo dataset using the command below:

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ ./core/gdrn_modeling/test_gdrn.sh ./configs/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo.py 0 ./output/gdrn/lmo_pbr/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_lmo/model_final_wo_optim.pth

```
I am running the following command to visualize the results

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ python  core/gdrn_modeling/tools/lmo/lmo_1_compute_fps.py
/home/mona/.local/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:586: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_obj_im_c(K, t):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:765: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xyxy_from_pose(points, pose, K, width=640, height=480, clip=False):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:793: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xyxy_from_pose_v2(points, pose, K, width=640, height=480, clip=False):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:822: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xywh_from_pose(points, pose, K, width=640, height=480, clip=False):
  0%|                                                                                                                                                                                 | 0/8 [00:00<?, ?it/s]1
5
 25%|██████████████████████████████████████████▎                                                                                                                              | 2/8 [00:00<00:00,  8.02it/s]6
 38%|███████████████████████████████████████████████████████████████▍                                                                                                         | 3/8 [00:00<00:00,  7.85it/s]8
 50%|████████████████████████████████████████████████████████████████████████████████████▌                                                                                    | 4/8 [00:00<00:00,  8.41it/s]9
10
 75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 6/8 [00:00<00:00,  8.85it/s]11
12
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  9.43it/s]
saved to /home/mona/gdrnpp_bop2022/datasets/BOP_DATASETS/lmo/models/fps_points.pkl
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ python core/gdrn_modeling/tools/lmo/lmo_3_vis_poses_full.py 
/home/mona/.local/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:586: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_obj_im_c(K, t):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:765: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xyxy_from_pose(points, pose, K, width=640, height=480, clip=False):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:793: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xyxy_from_pose_v2(points, pose, K, width=640, height=480, clip=False):
/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/../../../../lib/pysixd/misc.py:822: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def compute_2d_bbox_xywh_from_pose(points, pose, K, width=640, height=480, clip=False):
Creating GL context for Cuda device 0
;(egl_renderer) Loaded EGL version: 1.5.
  0%|                                                                                                                                                                                 | 0/8 [00:00<?, ?it/s][0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000001.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000001.ply loaded cache file: .cache/5a69126f0e708423031ae00695ad654a_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.6901960968971252
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000005.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000005.ply loaded cache file: .cache/2a63b9c7db7d4cb071cdae2803cc9785_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.9137254953384399
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000006.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000006.ply loaded cache file: .cache/c22328d3bc0a315a6c30d71ec5721697_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.9098039269447327
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000008.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000008.ply loaded cache file: .cache/b87ccbce6c3f76097ebc6e36e725b843_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.7843137383460999
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000009.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000009.ply loaded cache file: .cache/60dbff1e143e852cd74727cfdd8ee3c5_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.9529411792755127
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000010.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000010.ply loaded cache file: .cache/64a98ada262b40dba88884049926d85d_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.9372549057006836
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000011.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000011.ply loaded cache file: .cache/0c31b6adc192f9379f49e053fcce6868_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.800000011920929
[0103_140139@egl_renderer_v3.py:558] datasets/BOP_DATASETS/lmo/models/obj_000012.ply
[0103_140139@meshutil.py:403] datasets/BOP_DATASETS/lmo/models/obj_000012.ply loaded cache file: .cache/55aff959da94ec771030b987311bfce2_load_mesh_pysixd.pkl
[0103_140139@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0103_140139@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0103_140139@egl_renderer_v3.py:585] colors: 0.4431372582912445
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 159.52it/s]
output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl
Traceback (most recent call last):
  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/tools/lmo/lmo_3_vis_poses_full.py", line 64, in <module>
    preds = mmcv.load(pred_path)
  File "/home/mona/.local/lib/python3.10/site-packages/mmcv/fileio/io.py", line 67, in load
    with BytesIO(file_client.get(file)) as f:
  File "/home/mona/.local/lib/python3.10/site-packages/mmcv/fileio/file_client.py", line 1017, in get
    return self.client.get(filepath)
  File "/home/mona/.local/lib/python3.10/site-packages/mmcv/fileio/file_client.py", line 538, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl'

```

Why is this file missing after the inference?

**Comment by monajalal** [comment]
https://github.com/shanice-l/gdrnpp_bop2022/issues/110#issuecomment-1904240958
