### ISSUE TITLE
GDRN_double_mask is not defined!

### ISSUE THREAD

**Issue by Sar-thak-3** [shanice-l/gdrnpp_bop2022#119]
```
20240604_125201|ERR|__main__@235: An error has been caught in function '<module>', process 'MainProcess' (3353266), thread 'MainThread' (131120621827904):
Traceback (most recent call last):

> File "./core/gdrn_modeling/main_gdrn.py", line 235, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py', dist_u...
    └ <function main at 0x773f8c99c3a0>

  File "./core/gdrn_modeling/main_gdrn.py", line 201, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/home/yashwant/anaconda3/envs/gdrnpp/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py', dist_...
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x773f8c991ee0>>, <bound m...
  File "/home/yashwant/anaconda3/envs/gdrnpp/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py', dist_...
           └ <bound method Lite.run of <__main__.Lite object at 0x773f8c991ee0>>

  File "./core/gdrn_modeling/main_gdrn.py", line 160, in run
    model, optimizer = eval(cfg.MODEL.POSE_NET.NAME).build_model_optimizer(cfg, is_test=args.eval_only)
                            │                                              │            │    └ True
                            │                                              │            └ Namespace(config_file='configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py', dist_u...
                            │                                              └ Config (path: configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py): {'OUTPUT_ROOT':...
                            └ Config (path: configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py): {'OUTPUT_ROOT':...

  File "<string>", line 1, in <module>

NameError: name 'GDRN_double_mask' is not defined
20240604_125201|DBG|filelock._api@254: Attempting to acquire lock 131120610323904 on /home/sarthak/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@257: Lock 131120610323904 acquired on /home/sarthak/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@286: Attempting to release lock 131120610323904 on /home/sarthak/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@289: Lock 131120610323904 released on /home/sarthak/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@254: Attempting to acquire lock 131117032084096 on /home/sarthak/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@257: Lock 131117032084096 acquired on /home/sarthak/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@286: Attempting to release lock 131117032084096 on /home/sarthak/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
20240604_125201|DBG|filelock._api@289: Lock 131117032084096 released on /home/sarthak/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
```

Installed Libraries
```
Package                   Version
------------------------- --------------------
absl-py                   2.1.0
addict                    2.4.0
aiohttp                   3.9.5
aiosignal                 1.3.1
albucore                  0.0.7
albumentations            1.4.8
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.2.0
backcall                  0.2.0
black                     24.4.2
blinker                   1.8.2
cachetools                5.3.3
cattrs                    23.2.3
certifi                   2024.6.2
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
comm                      0.2.2
ConfigArgParse            1.7
contourpy                 1.1.1
cryptography              42.0.7
cycler                    0.12.1
Cython                    3.0.10
dash                      2.17.0
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
decorator                 5.1.1
deepspeed                 0.14.2
detectron2                0.6
distro                    1.9.0
docformatter              1.7.5
einops                    0.8.0
exceptiongroup            1.2.1
executing                 2.0.1
fairscale                 0.4.13
fastjsonschema            2.19.1
filelock                  3.13.1
Flask                     3.0.3
flatbuffers               24.3.25
fonttools                 4.53.0
freetype-py               2.4.0
frozenlist                1.4.1
fsspec                    2024.2.0
fvcore                    0.1.5.post20221221
glfw                      2.7.0
google-auth               2.29.0
google-auth-oauthlib      1.0.0
grpcio                    1.64.0
hjson                     3.1.0
hsluv                     5.0.4
hydra-core                1.3.2
idna                      3.7
imagecorruptions          1.1.2
imageio                   2.34.1
imageio-ffmpeg            0.5.1
imgaug                    0.4.0
importlib_metadata        7.1.0
importlib_resources       6.4.0
iniconfig                 2.0.0
iopath                    0.1.9
ipdb                      0.13.13
ipython                   8.12.3
ipywidgets                8.1.3
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.3
joblib                    1.4.2
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_core              5.7.2
jupyterlab_widgets        3.0.11
kiwisolver                1.4.5
lazy_loader               0.4
lightning-utilities       0.11.2
llvmlite                  0.41.1
loguru                    0.7.2
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.7.5
matplotlib-inline         0.1.7
mdurl                     0.1.2
meshio                    5.3.5
meshplex                  0.19.5
mmcv-full                 1.7.2
mpmath                    1.3.0
multidict                 6.0.5
mypy-extensions           1.0.0
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.0
ninja                     1.11.1.1
npx                       0.1.2
numba                     0.58.1
numpy                     1.24.4
nvidia-cublas-cu11        11.11.3.6
nvidia-cuda-cupti-cu11    11.8.87
nvidia-cuda-nvrtc-cu11    11.8.89
nvidia-cuda-runtime-cu11  11.8.89
nvidia-cudnn-cu11         8.7.0.84
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.3.0.86
nvidia-cusolver-cu11      11.4.1.48
nvidia-cusparse-cu11      11.7.5.86
nvidia-nccl-cu11          2.20.5
nvidia-nvtx-cu11          11.8.86
oauthlib                  3.2.2
omegaconf                 2.3.0
onnx                      1.16.1
onnx-simplifier           0.3.5
onnxoptimizer             0.3.13
onnxruntime               1.8.0
open3d                    0.18.0
opencv-python             4.10.0.82
opencv-python-headless    4.10.0.82
OpenEXR                   3.2.4
opt-einsum                3.3.0
packaging                 24.0
pandas                    2.0.3
parso                     0.8.4
pathspec                  0.12.1
pexpect                   4.9.0
pickleshare               0.7.5
Pillow-SIMD               9.0.0.post1
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.2
plotly                    5.22.0
pluggy                    1.5.0
plyfile                   1.0.3
portalocker               2.8.2
prompt_toolkit            3.0.45
protobuf                  5.27.0
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
py-cpuinfo                9.0.0
py-machineid              0.5.1
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pyassimp                  4.1.3
pycocotools               2.0.7
pycparser                 2.22
pydantic                  2.7.3
pydantic_core             2.18.4
pyDeprecate               0.3.2
Pygments                  2.18.0
pynvml                    11.5.0
PyOpenGL                  3.1.7
PyOpenGL-accelerate       3.1.7
pyparsing                 3.1.2
pypng                     0.20220715.0
pyquaternion              0.9.9
pyro-api                  0.1.2
pyro-ppl                  1.4.0
pytest                    8.2.1
pytest-runner             6.0.1
python-dateutil           2.9.0.post0
python-package-info       0.0.3
pytorch-lightning         1.6.0
pytorch3d                 0.3.0
pytz                      2024.1
PyWavelets                1.4.1
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.32.3
requests-cache            1.2.0
requests-oauthlib         2.0.0
retrying                  1.3.4
rich                      13.7.1
rich-argparse             1.5.0
rpds-py                   0.18.1
rsa                       4.9
scikit-image              0.21.0
scikit-learn              1.3.2
scipy                     1.10.1
setproctitle              1.3.3
setuptools                69.5.1
shapely                   2.0.4
six                       1.16.0
stack-data                0.6.3
stonefish-license-manager 0.4.29
sympy                     1.12
tabulate                  0.9.0
tenacity                  8.3.0
tensorboard               2.14.0
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
termcolor                 2.4.0
thop                      0.1.1.post2209072238
threadpoolctl             3.5.0
tifffile                  2023.7.10
timm                      0.6.7
tomli                     2.0.1
torch                     2.3.0+cu118
torchaudio                2.3.0+cu118
torchmetrics              1.4.0.post0
torchvision               0.18.0+cu118
tqdm                      4.66.4
traitlets                 5.14.3
transforms3d              0.4.1
triton                    2.3.0
typing_extensions         4.9.0
tzdata                    2024.1
ujson                     5.10.0
untokenize                0.1.1
url-normalize             1.4.3
urllib3                   2.2.1
vispy                     0.14.2
wcwidth                   0.2.13
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
x21                       0.4.33
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.19.1
```

**Comment by shanice-l** [comment]
It's strange. I think I have added this model to the repo.
