### ISSUE TITLE
lmo_2_vis_poses.py FileNotFoundError: [Errno 2] No such file or directory: 'output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl'

### ISSUE THREAD

**Issue by dayu225** [shanice-l/gdrnpp_bop2022#121]
Please tell me why there is no PKL file
need help @wangg12 
`/home/dayu/anaconda3/envs/gdrnpp38/bin/python /home/dayu/gdrnpp_bop2022-main/core/gdrn_modeling/tools/lmo/lmo_2_vis_poses.py 
/home/dayu/anaconda3/envs/gdrnpp38/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Creating GL context for Cuda device 0
;(egl_renderer) Loaded EGL version: 1.5.
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000001.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000001.ply loaded cache file: .cache/18d76999d4800a78888c90915c9db9f8_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.6901960968971252
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000005.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000005.ply loaded cache file: .cache/960e2e2ac97e48cfbefa8525561c0130_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.9137254953384399
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000006.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000006.ply loaded cache file: .cache/87b0e962ea1f862562927f389041208a_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.9098039269447327
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000008.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000008.ply loaded cache file: .cache/6cf190ac7b6d15b72c7b97db0f8d8f9d_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.7843137383460999
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000009.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000009.ply loaded cache file: .cache/65b9819b68b4ef317facb6e38e63e53f_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.9529411792755127
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000010.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000010.ply loaded cache file: .cache/6103dde2cf69c15e6d6002be577b60c3_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.9372549057006836
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000011.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000011.ply loaded cache file: .cache/081214274f281ce0049e239f1aed3a16_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.800000011920929
[0723_155320@egl_renderer_v3.py:558] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000012.ply
[0723_155320@meshutil.py:400] /home/dayu/gdrnpp_bop2022-main/datasets/BOP_DATASETS/lmo/models/obj_000012.ply loaded cache file: .cache/80651473d3e5048f325c9f66fdf983ab_load_mesh_pysixd.pkl
[0723_155320@egl_renderer_v3.py:567] is_textured: False | is_cad: False | is_materialed: False
[0723_155320@egl_renderer_v3.py:570] ['vertices', 'normals', 'colors', 'faces', 'texturecoords', 'is_cad', 'uMatDiffuse', 'uMatSpecular', 'uMatAmbient', 'uMatShininess']
[0723_155320@egl_renderer_v3.py:585] colors: 0.4431372582912445
output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl
100%|██████████| 8/8 [00:00<00:00, 393.49it/s]
Traceback (most recent call last):
  File "/home/dayu/gdrnpp_bop2022-main/core/gdrn_modeling/tools/lmo/lmo_2_vis_poses.py", line 69, in <module>
    preds = mmcv.load(pred_path)
  File "/home/dayu/anaconda3/envs/gdrnpp38/lib/python3.8/site-packages/mmcv/fileio/io.py", line 67, in load
    with BytesIO(file_client.get(file)) as f:
  File "/home/dayu/anaconda3/envs/gdrnpp38/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 1017, in get
    return self.client.get(filepath)
  File "/home/dayu/anaconda3/envs/gdrnpp38/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 538, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/inference_model_final/lmo_test/a6-cPnP-AugAAETrunc-BG0.5-lmo-real-pbr0.1-40e-test_lmo_test_preds.pkl'`

**Comment by wangg12** [comment]
Have you run inference to get the pkl file in your output folder?

**Comment by shanice-l** [comment]
You should first run prediction to generate the pkl file and then do visualization.
