### ISSUE TITLE
Index out of bounds when loading in Dataset for training

### ISSUE THREAD

**Issue by Martin9797** [shanice-l/gdrnpp_bop2022#30]
Hi, 
I am getting an Index out of bounds error when starting the training for pose estimation on tless Dataset with command:
`./core/gdrn_modeling/train_gdrn.sh configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py 0`

The error usually occurs a few times  when trying to train, but after a couple tries it starts to train without raising  the error again. Sometimes also a Segmentation fault is thrown.  
Here the index error:

```
20230131_152655|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (127486), thread 'MainThread' (140000745686208):
Traceback (most recent call last):

> File "./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127.0...
    └ <function main at 0x7f5399fdaaf0>

  File "./core/gdrn_modeling/main_gdrn.py", line 199, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127....
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7f53d3435070>>, <bound m...
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127....
           └ <bound method Lite.run of <__main__.Lite object at 0x7f53d3435070>>

  File "./core/gdrn_modeling/main_gdrn.py", line 185, in run
    self.do_train(cfg, args, model, optimizer, renderer=renderer, resume=args.resume)
    │    │        │    │     │      │                   │                │    └ False
    │    │        │    │     │      │                   │                └ Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127.0...
    │    │        │    │     │      │                   └ <lib.egl_renderer.egl_renderer_v3.EGLRenderer object at 0x7f5397dcc040>
    │    │        │    │     │      └ LiteRanger (
    │    │        │    │     │        Parameter Group 0
    │    │        │    │     │            N_sma_threshhold: 5
    │    │        │    │     │            alpha: 0.5
    │    │        │    │     │            betas: (0.95, 0.999)
    │    │        │    │     │            eps: 1e-05
    │    │        │    │     │            initial_lr:...
    │    │        │    │     └ _LiteModule(
    │    │        │    │         (_module): GDRN_DoubleMask(
    │    │        │    │           (backbone): FeatureListNet(
    │    │        │    │             (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
    │    │        │    └ Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127.0...
    │    │        └ Config (path: configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py): {'OUTPUT_ROOT': 'output', 'OUT...
    │    └ <function GDRN_Lite.do_train at 0x7f539a341820>
    └ <__main__.Lite object at 0x7f53d3435070>

  File "/home/faps/GDRNPP_pose_est/pose_est_gdrnpp/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 275, in do_train
    data = next(data_loader_iter)
                └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f53971af250>

  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f53e0bb5b80>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f53971af250>
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f537a1d97c0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f53e0bb5ca0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f53971af250>
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f547514a790>
    └ <torch._utils.ExceptionWrapper object at 0x7f537a1d97c0>
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
          └ IndexError('Caught IndexError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/home/fap...

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/faps/anaconda3/envs/GDRNPP/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/faps/GDRNPP_pose_est/pose_est_gdrnpp/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader_online.py", line 765, in __getitem__
    dataset_dict = self._get_sample_dict(idx)
  File "/home/faps/GDRNPP_pose_est/pose_est_gdrnpp/core/gdrn_modeling/../../core/base_data_loader.py", line 118, in _get_sample_dict
    start_addr = 0 if idx == 0 else self._addr[idx - 1].item()
IndexError: index 181319007 is out of bounds for axis 0 with size 17223

```
The  index changes when trying again. 

Has this happened to anyone before? Or  do you have any idea what might cause this?

Thank you!

**Comment by shanice-l** [comment]
I've never met this error before, so I assume that's an environmental problem.

**Comment by Martin9797** [comment]
Can you  tell me which exact versions of python, pytorch, torchvision and cuda you have used in combination?

**Comment by 3bsamad** [comment]
If you get a segmentation fault (core dump) error, uninstall detectron2 and reinstall the exact version that matches your pytorch, lightning and cuda installations. This worked for me.

**Comment by shanice-l** [comment]
> Can you tell me which exact versions of python, pytorch, torchvision and cuda you have used in combination?

python 3.7.4 + torchvision 0.11.2 + pytorch 1.10.0 + cuda 11.4

**Comment by Martin9797** [comment]
Thank you, the error already went away after downgrading to python 3.7 and pytorch 1.12.0 with cuda 11.6. Since I reinstalled detectron2 and basically everything else I am not sure if that was part of the problem, but the index error and also segmentation fault have not been coming up since.

**Comment by shanice-l** [comment]
Downgrading pytorch and installing the corresponding detectron2 would be helpful.

**Comment by george66s** [comment]
Occasionally ran into index out of bounds issue like below:

IndexError: index -4735985000530474587 is out of bounds for axis 0 with size 1030285

It's quite strange how can index go negative.

My environment is python 3.8.16 + torch 1.13.1 + torchvision 0.14.1 + cuda 11.6.
