### ISSUE TITLE
install lietorch during environment  creation (branch : pose_refine)

### ISSUE THREAD

**Issue by mqtjean** [shanice-l/gdrnpp_bop2022#31]
Hi, 

I am trying to use the iterative refinement in the `pose_refine` branch, but I can't create the required environment using :
`conda env create -f environment.yaml`

Indeed, I get the following error : 

```
× Encountered error while trying to install package.  
╰─> lietorch
```
So, I installed it with conda : 

`conda install -c lietorch lietorch`

But then when I run training I get the following error :

```
Traceback (most recent call last):
  File "/home/jmoquet/gdrnpp_bop2022_refine/gdrnpp_bop2022/train.py", line 18, in <module>
    from lietorch import SE3
  File "/home/jmoquet/anaconda3/envs/refine/lib/python3.9/site-packages/lietorch/__init__.py", line 75, in <module>
    _init_backend()
  File "/home/jmoquet/anaconda3/envs/refine/lib/python3.9/site-packages/lietorch/__init__.py", line 55, in _init_backend
    torch.ops.load_library(libpath)
  File "/home/jmoquet/anaconda3/envs/refine/lib/python3.9/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/jmoquet/anaconda3/envs/refine/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```
I want to know if this branch is up to date and if you know how to install the correct version of lietorch library.

Thanks

**Comment by shanice-l** [comment]
You can build lietorch from their official github repo ([link](https://github.com/princeton-vl/lietorch))

**Comment by mqtjean** [comment]
Thank you for your answer.
I still have trouble to install lietorch on a new environment on Ubuntu 22.04 with python 3.8 - cuda 12.0 - pytorch 1.13 . But I think this is not of your concern, I will investigate further.

**Comment by mqtjean** [comment]
Most of my problem during environment creation were due to cuda version conflict. 

I created a new conda env making sure I had only one version of cuda (for me 12.0), after this I installed lietorch using `pip install git+https://github.com/princeton-vl/lietorch.git` and it worked fine
