### ISSUE TITLE
missing test_targets_bop19.json

### ISSUE THREAD

**Issue by freLorbeer** [shanice-l/gdrnpp_bop2022#72]
Hello,

I followed the Dataset preparation instructions from the ReadMe to download all the data test boxes etc. The training runs till the end (100 epochs) successfully. 
Now I get the following error message:
FileNotFoundError: [Errno 2] No such file or directory: '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'

Where do I find this json file? I couldn't find any according json file at the OneDrive folders. Or am I supposed to rename e.g. the yolox_x_640_tless_pbr_tless_bop_test.json file?

Thanks for your work and your upcoming answer!

Here ist the full Traceback:

`20231025_103331|core.gdrn_modeling.datasets.tless_bop_test@105: loading dataset dicts: tless_bop_test_primesense
20231025_103331|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (64), thread 'MainThread' (140154818459456):
Traceback (most recent call last):

> File "./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127.0...
    └ <function main at 0x7f775cd9d1f0>

  File "./core/gdrn_modeling/main_gdrn.py", line 199, in main
    Lite(
    └ <class '__main__.Lite'>

  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127....
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7f775cd9b9a0>>, <bound m...

  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py', dist_url='tcp://127....
           └ <bound method Lite.run of <__main__.Lite object at 0x7f775cd9b9a0>>

  File "./core/gdrn_modeling/main_gdrn.py", line 189, in run
    return self.do_test(cfg, model)
           │    │       │    └ _LiteModule(
           │    │       │        (_module): GDRN_DoubleMask(
           │    │       │          (backbone): FeatureListNet(
           │    │       │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
           │    │       └ Config (path: configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py): {'OUTPUT_ROOT': 'output', 'OUT...
           │    └ <function GDRN_Lite.do_test at 0x7f775d11b160>
           └ <__main__.Lite object at 0x7f775cd9b9a0>

  File "/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 157, in do_test
    data_loader = build_gdrn_test_loader(cfg, dataset_name, train_objs=evaluator.train_objs)
                  │                      │    │                        │         └ ['1']
                  │                      │    │                        └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f77c94bfca0>
                  │                      │    └ 'tless_bop_test_primesense'
                  │                      └ Config (path: configs/gdrn/tlessPbrSO/convnext_AugCosyAAEGray_DMask_amodalClipBox_tless/1.py): {'OUTPUT_ROOT': 'output', 'OUT...
                  └ <function build_gdrn_test_loader at 0x7f775d157ca0>

  File "/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader.py", line 914, in build_gdrn_test_loader
    dataset_dicts = get_detection_dataset_dicts(
                    └ <function get_detection_dataset_dicts at 0x7f77b15ecee0>

  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/build.py", line 253, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │                                     └ ['tless_bop_test_primesense']
                     │              └ <function _DatasetCatalog.get at 0x7f77b15d6280>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...

  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/build.py", line 253, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
                     │              │   │                 └ 'tless_bop_test_primesense'
                     │              │   └ 'tless_bop_test_primesense'
                     │              └ <function _DatasetCatalog.get at 0x7f77b15d6280>
                     └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...

  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/catalog.py", line 58, in get
    return f()
           └ <core.gdrn_modeling.datasets.tless_bop_test.TLESS_BOP_TEST_Dataset object at 0x7f775cd9b940>

  File "/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/datasets/tless_bop_test.py", line 110, in __call__
    targets = mmcv.load(self.ann_file)
              │    │    │    └ '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'
              │    │    └ <core.gdrn_modeling.datasets.tless_bop_test.TLESS_BOP_TEST_Dataset object at 0x7f775cd9b940>
              │    └ <function load at 0x7f77a92eb3a0>
              └ <module 'mmcv' from '/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py'>

  File "/usr/local/lib/python3.8/dist-packages/mmcv/fileio/io.py", line 64, in load
    with StringIO(file_client.get_text(file)) as f:
         │        │           │        └ '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'
         │        │           └ <function FileClient.get_text at 0x7f77a92de940>
         │        └ <mmcv.fileio.file_client.FileClient object at 0x7f775cd9bca0>
         └ <class '_io.StringIO'>

  File "/usr/local/lib/python3.8/dist-packages/mmcv/fileio/file_client.py", line 1027, in get_text
    return self.client.get_text(filepath, encoding)
           │    │      │        │         └ 'utf-8'
           │    │      │        └ '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'
           │    │      └ <function HardDiskBackend.get_text at 0x7f77a92e5c10>
           │    └ <mmcv.fileio.file_client.HardDiskBackend object at 0x7f775cd9bb20>
           └ <mmcv.fileio.file_client.FileClient object at 0x7f775cd9bca0>

  File "/usr/local/lib/python3.8/dist-packages/mmcv/fileio/file_client.py", line 552, in get_text
    with open(filepath, encoding=encoding) as f:
              │                  └ 'utf-8'
              └ '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'

FileNotFoundError: [Errno 2] No such file or directory: '/gdrnpp_bop2022/datasets/BOP_DATASETS/tless/test_targets_bop19.json'
`

**Comment by freLorbeer** [comment]
never mind, I found the file in the base archive of the tless dataset
