### ISSUE TITLE
AssertionError: gdrnpp_bop2022/datasets/BOP_DATASETS/hb/models/fps_points.pkl

### ISSUE THREAD

**Issue by belalhmedan90** [shanice-l/gdrnpp_bop2022#87]
When trying to **train** the **pose estimation** using **hb_pbr dataset**, I get an error: `AssertionError: /home/aime/belal_ws/gdrnpp_bop2022/datasets/BOP_DATASETS/hb/models/fps_points.pkl`, can you please guide me ho can I solve it please? thanks in advance.

```sh
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 275, in do_train
    data = next(data_loader_iter)
                └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f363ed6f0d0>

  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f3630b029d0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f363ed6f0d0>
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f363f287880>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f3630b02af0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f363ed6f0d0>
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f36b5e72280>
    └ <torch._utils.ExceptionWrapper object at 0x7f363f287880>
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aime/belal_ws/pose6d_venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader_online.py", line 764, in __getitem__
    processed_data = self.read_data(dataset_dict)
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../core/base_data_loader.py", line 93, in read_data
    return self.read_data_train(dataset_dict)
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader_online.py", line 548, in read_data_train
    fps_points = self._get_fps_points(dataset_name)[roi_cls]
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/datasets/data_loader_online.py", line 211, in _get_fps_points
    loaded_fps_points = data_ref.get_fps_points()
  File "/home/aime/belal_ws/gdrnpp_bop2022/core/gdrn_modeling/../../ref/hb.py", line 108, in get_fps_points
    assert osp.exists(fps_points_path), fps_points_path
AssertionError: /home/aime/belal_ws/gdrnpp_bop2022/datasets/BOP_DATASETS/hb/models/fps_points.pkl
```

```sh
ls /home/aime/belal_ws/gdrnpp_bop2022/datasets/BOP_DATASETS/hb/models/
models_hb_bop_train_pbr.pkl  obj_000001.ply  obj_000004.ply  obj_000007.ply  obj_000010.ply  obj_000013.ply  obj_000016.ply  obj_000019.ply  obj_000022.ply  obj_000025.ply  obj_000028.ply  obj_000031.ply
models_hb_pbr_train.pkl      obj_000002.ply  obj_000005.ply  obj_000008.ply  obj_000011.ply  obj_000014.ply  obj_000017.ply  obj_000020.ply  obj_000023.ply  obj_000026.ply  obj_000029.ply  obj_000032.ply
models_info.json             obj_000003.ply  obj_000006.ply  obj_000009.ply  obj_000012.ply  obj_000015.ply  obj_000018.ply  obj_000021.ply  obj_000024.ply  obj_000027.ply  obj_000030.ply  obj_000033.ply
```

**Comment by shanice-l** [comment]
You can generate this file by yourself using [code](https://github.com/shanice-l/gdrnpp_bop2022/blob/main/core/gdrn_modeling/tools/hb/hb_1_compute_fps.py).

**Comment by belalhmedan90** [comment]
@shanice-l thanks, it solved my problem
