### ISSUE TITLE
ImportError: cannot import name 'Config' from 'mmcv' (/home/mona/.local/lib/python3.10/site-packages/mmcv/__init__.py)

### ISSUE THREAD

**Issue by monajalal** [shanice-l/gdrnpp_bop2022#89]
I get this error. Could you suggest how to fix?

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ ./core/gdrn_modeling/train_gdrn.sh configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py 0
++ dirname ./core/gdrn_modeling/train_gdrn.sh
+ this_dir=./core/gdrn_modeling
+ CFG=configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py
+ CUDA_VISIBLE_DEVICES=0
+ IFS=,
+ read -ra GPUS
+ NGPU=1
+ echo 'use gpu ids: 0 num gpus: 1'
use gpu ids: 0 num gpus: 1
+ NCCL_DEBUG=INFO
+ OMP_NUM_THREADS=1
+ MKL_NUM_THREADS=1
+ PYTHONPATH=./core/gdrn_modeling/../..:/home/mona/realsense-ros/install/realsense2_camera_msgs/local/lib/python3.10/dist-packages:/opt/ros/humble/lib/python3.10/site-packages:/opt/ros/humble/local/lib/python3.10/dist-packages
+ CUDA_VISIBLE_DEVICES=0
+ python ./core/gdrn_modeling/main_gdrn.py --config-file configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py --num-gpus 1
/home/mona/.local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 16, in <module>
    from mmcv import Config
ImportError: cannot import name 'Config' from 'mmcv' (/home/mona/.local/lib/python3.10/site-packages/mmcv/__init__.py)

```

I installed

```
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1/index.html
```

based on the instructions here

https://mmcv.readthedocs.io/en/latest/get_started/installation.html

I get the same error if I install it using `mim`

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ mim install mmcv==2.1.0 
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/index.html
Collecting mmcv==2.1.0
  Downloading https://download.openmmlab.com/mmcv/dist/cu118/torch2.1.0/mmcv-2.1.0-cp310-cp310-manylinux1_x86_64.whl (99.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.3/99.3 MB 12.7 MB/s eta 0:00:00
Requirement already satisfied: addict in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (2.4.0)
Requirement already satisfied: mmengine>=0.3.0 in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (0.10.1)
Requirement already satisfied: numpy in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (1.26.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from mmcv==2.1.0) (21.3)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from mmcv==2.1.0) (9.0.1)
Requirement already satisfied: pyyaml in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (6.0.1)
Requirement already satisfied: yapf in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (0.40.2)
Requirement already satisfied: opencv-python>=3 in /home/mona/.local/lib/python3.10/site-packages (from mmcv==2.1.0) (4.8.1.78)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from mmengine>=0.3.0->mmcv==2.1.0) (3.5.1)
Requirement already satisfied: rich in /home/mona/.local/lib/python3.10/site-packages (from mmengine>=0.3.0->mmcv==2.1.0) (13.4.2)
Requirement already satisfied: termcolor in /home/mona/.local/lib/python3.10/site-packages (from mmengine>=0.3.0->mmcv==2.1.0) (2.4.0)
Requirement already satisfied: importlib-metadata>=6.6.0 in /home/mona/.local/lib/python3.10/site-packages (from yapf->mmcv==2.1.0) (7.0.0)
Requirement already satisfied: platformdirs>=3.5.1 in /home/mona/.local/lib/python3.10/site-packages (from yapf->mmcv==2.1.0) (4.1.0)
Requirement already satisfied: tomli>=2.0.1 in /home/mona/.local/lib/python3.10/site-packages (from yapf->mmcv==2.1.0) (2.0.1)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=6.6.0->yapf->mmcv==2.1.0) (1.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/mona/.local/lib/python3.10/site-packages (from rich->mmengine>=0.3.0->mmcv==2.1.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/mona/.local/lib/python3.10/site-packages (from rich->mmengine>=0.3.0->mmcv==2.1.0) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /home/mona/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->mmengine>=0.3.0->mmcv==2.1.0) (0.1.2)
Installing collected packages: mmcv
Successfully installed mmcv-2.1.0
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ ./core/gdrn_modeling/train_gdrn.sh configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py 0
++ dirname ./core/gdrn_modeling/train_gdrn.sh
+ this_dir=./core/gdrn_modeling
+ CFG=configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py
+ CUDA_VISIBLE_DEVICES=0
+ IFS=,
+ read -ra GPUS
+ NGPU=1
+ echo 'use gpu ids: 0 num gpus: 1'
use gpu ids: 0 num gpus: 1
+ NCCL_DEBUG=INFO
+ OMP_NUM_THREADS=1
+ MKL_NUM_THREADS=1
+ PYTHONPATH=./core/gdrn_modeling/../..:/home/mona/realsense-ros/install/realsense2_camera_msgs/local/lib/python3.10/dist-packages:/opt/ros/humble/lib/python3.10/site-packages:/opt/ros/humble/local/lib/python3.10/dist-packages
+ CUDA_VISIBLE_DEVICES=0
+ python ./core/gdrn_modeling/main_gdrn.py --config-file configs/gdrn/ycbv/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_ycbv.py --num-gpus 1
/home/mona/.local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 16, in <module>
    from mmcv import Config
ImportError: cannot import name 'Config' from 'mmcv' (/home/mona/.local/lib/python3.10/site-packages/mmcv/__init__.py)

```

```
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcv
>>> dir(mmcv)
['BaseTransform', 'Cache', 'CenterCrop', 'Color', 'Compose', 'ImageToTensor', 'KeyMapper', 'LoadAnnotations', 'LoadImageFromFile', 'MultiScaleFlipAug', 'Normalize', 'Pad', 'RandomApply', 'RandomChoice', 'RandomChoiceResize', 'RandomFlip', 'RandomGrayscale', 'RandomResize', 'Resize', 'TRANSFORMS', 'TestTimeAug', 'ToTensor', 'TransformBroadcaster', 'VideoReader', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'adjust_brightness', 'adjust_color', 'adjust_contrast', 'adjust_hue', 'adjust_lighting', 'adjust_sharpness', 'arraymisc', 'auto_contrast', 'bgr2gray', 'bgr2hls', 'bgr2hsv', 'bgr2rgb', 'bgr2ycbcr', 'clahe', 'color_val', 'concat_video', 'convert_video', 'cut_video', 'cutout', 'dequantize', 'dequantize_flow', 'flow2rgb', 'flow_from_bytes', 'flow_warp', 'flowread', 'flowshow', 'flowwrite', 'frames2video', 'gray2bgr', 'gray2rgb', 'hls2bgr', 'hsv2bgr', 'image', 'imconvert', 'imcrop', 'imdenormalize', 'imequalize', 'imflip', 'imflip_', 'imfrombytes', 'iminvert', 'imnormalize', 'imnormalize_', 'impad', 'impad_to_multiple', 'imread', 'imrescale', 'imresize', 'imresize_like', 'imresize_to_multiple', 'imrotate', 'imshear', 'imshow', 'imshow_bboxes', 'imshow_det_bboxes', 'imtranslate', 'imwrite', 'lut_transform', 'make_color_wheel', 'parse_version_info', 'posterize', 'quantize', 'quantize_flow', 'rescale_size', 'resize_video', 'rgb2bgr', 'rgb2gray', 'rgb2ycbcr', 'solarize', 'sparse_flow_from_bytes', 'supported_backends', 'tensor2imgs', 'to_tensor', 'transforms', 'use_backend', 'version', 'version_info', 'video', 'visualization', 'ycbcr2bgr', 'ycbcr2rgb']

```

**Comment by monajalal** [comment]
(gdrnpp) mona@ada:~/gdrnpp_bop2022$ pip install mmcv==1.7.1 --no-cache-dir --no-deps -U --force-reinstall
