### ISSUE TITLE
RuntimeError: output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/tless_bop_test_primesense/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test/error:vsd_ntop:-1_delta:15.000_tau:0.050 does not exist.

### ISSUE THREAD

**Issue by monajalal** [shanice-l/gdrnpp_bop2022#99]
Could you please help with this error?

```

(gdrnpp) mona@ada:~/gdrnpp_bop2022$ ./core/gdrn_modeling/test_gdrn.sh ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py 0 ./output/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/model_final_wo_optim.pth


MESSAGES

  0%|          | 0/1 [00:00<?, ?it/s]
20240103_100816|core.gdrn_modeling.engine.test_utils@411: ************convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test *********************
20240103_100816|core.gdrn_modeling.engine.test_utils@417: 
objects  mssd_0.050:0.500
1        63.06
2        65.90
3        72.08
4        65.19
5        84.95
6        84.08
7        84.08
8        92.80
9        90.12
10       85.17
11       77.43
12       79.06
13       65.29
14       70.75
15       61.71
16       83.14
17       88.97
18       82.95
19       72.09
20       72.62
21       76.57
22       66.28
23       81.81
24       83.18
25       82.00
26       83.54
27       84.06
28       81.51
29       91.33
30       75.90
Avg(30)  75.15
20240103_100816|WRN|core.gdrn_modeling.engine.test_utils@422: output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/tless_bop_test_primesense/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test/error:vsd_ntop:-1_delta:15.000_tau:0.050 does not exist.
20240103_100816|ERR|__main__@233: An error has been caught in function '<module>', process 'MainProcess' (62620), thread 'MainThread' (139986895367040):
Traceback (most recent call last):

> File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 233, in <module>
    main(args)
    │    └ Namespace(config_file='./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py', re...
    └ <function main at 0x7f4ffdf5e4d0>

  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 205, in main
    ).run(args, cfg)
          │     └ Config (path: ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py): {'OUTPUT_RO...
          └ Namespace(config_file='./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py', re...

  File "/home/mona/.local/lib/python3.10/site-packages/pytorch_lightning/lite/lite.py", line 408, in _run_impl
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py', r...
           └ functools.partial(<bound method LightningLite._run_with_strategy_setup of <__main__.Lite object at 0x7f4ffdbd1ae0>>, <bound m...
  File "/home/mona/.local/lib/python3.10/site-packages/pytorch_lightning/lite/lite.py", line 413, in _run_with_strategy_setup
    return run_method(*args, **kwargs)
           │           │       └ {}
           │           └ (Namespace(config_file='./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py', r...
           └ <bound method Lite.run of <__main__.Lite object at 0x7f4ffdbd1ae0>>

  File "/home/mona/gdrnpp_bop2022/./core/gdrn_modeling/main_gdrn.py", line 183, in run
    return self.do_test(cfg, model)
           │    │       │    └ _LiteModule(
           │    │       │        (_module): GDRN_DoubleMask(
           │    │       │          (backbone): FeatureListNet(
           │    │       │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
           │    │       └ Config (path: ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py): {'OUTPUT_RO...
           │    └ <function GDRN_Lite.do_test at 0x7f5004b88c10>
           └ <__main__.Lite object at 0x7f4ffdbd1ae0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/engine.py", line 159, in do_test
    results_i = gdrn_inference_on_dataset(cfg, model, data_loader, evaluator, amp_test=cfg.TEST.AMP_TEST)
                │                         │    │      │            │                   └ Config (path: ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py): {'OUTPUT_RO...
                │                         │    │      │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>
                │                         │    │      └ <pytorch_lightning.lite.wrappers._LiteDataLoader object at 0x7f4ff7744e20>
                │                         │    └ _LiteModule(
                │                         │        (_module): GDRN_DoubleMask(
                │                         │          (backbone): FeatureListNet(
                │                         │            (stem_0): Conv2d(3, 128, kernel_size=(4, 4),...
                │                         └ Config (path: ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py): {'OUTPUT_RO...
                └ <function gdrn_inference_on_dataset at 0x7f5004b427a0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 804, in gdrn_inference_on_dataset
    results = evaluator.evaluate()  # results is always None
              │         └ <function GDRN_Evaluator.evaluate at 0x7f5004b43760>
              └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 584, in evaluate
    return self._eval_predictions()
           │    └ <function GDRN_Evaluator._eval_predictions at 0x7f5004b437f0>
           └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/gdrn_evaluator.py", line 595, in _eval_predictions
    save_and_eval_results(self.cfg, results_all, self._output_dir, obj_ids=self.obj_ids)
    │                     │    │    │            │    │                    │    └ [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    │                     │    │    │            │    │                    └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>
    │                     │    │    │            │    └ 'output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/t...
    │                     │    │    │            └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>
    │                     │    │    └ {'iter0': [{'scene_id': '1', 'im_id': 1, 'obj_id': 2, 'score': tensor(0.9654, dtype=torch.float64), 'R': [-0.943906307220459,...
    │                     │    └ Config (path: ./configs/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless.py): {'OUTPUT_RO...
    │                     └ <core.gdrn_modeling.engine.gdrn_evaluator.GDRN_Evaluator object at 0x7f4ffdaf64d0>
    └ <function save_and_eval_results at 0x7f5004b42b90>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 73, in save_and_eval_results
    load_and_print_val_scores_tab(
    └ <function load_and_print_val_scores_tab at 0x7f5004b431c0>

  File "/home/mona/gdrnpp_bop2022/core/gdrn_modeling/../../core/gdrn_modeling/engine/test_utils.py", line 423, in load_and_print_val_scores_tab
    raise RuntimeError("{} does not exist.".format(score_root))
                                                   └ 'output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/t...

RuntimeError: output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/tless_bop_test_primesense/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test/error:vsd_ntop:-1_delta:15.000_tau:0.050 does not exist.


```

This is all I have:

```

(base) mona@ada:~/gdrnpp_bop2022$ tree  output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/tless_bop_test_primesense/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test
output/gdrn/tless/convnext_a6_AugCosyAAEGray_BG05_mlL1_DMask_amodalClipBox_classAware_tless/inference_model_final_wo_optim/tless_bop_test_primesense/convnext-a6-AugCosyAAEGray-BG05-mlL1-DMask-amodalClipBox-classAware-tless-test-iter0_tless-test
├── error:ad_ntop:-1
│   ├── errors_000001.json
│   ├── errors_000002.json
│   ├── errors_000003.json
│   ├── errors_000004.json
│   ├── errors_000005.json
│   ├── errors_000006.json
│   ├── errors_000007.json
│   ├── errors_000008.json
│   ├── errors_000009.json
│   ├── errors_000010.json
│   ├── errors_000011.json
│   ├── errors_000012.json
│   ├── errors_000013.json
│   ├── errors_000014.json
│   ├── errors_000015.json
│   ├── errors_000016.json
│   ├── errors_000017.json
│   ├── errors_000018.json
│   ├── errors_000019.json
│   ├── errors_000020.json
│   ├── matches_th:0.020_min-visib:-1.000.json
│   ├── matches_th:0.050_min-visib:-1.000.json
│   ├── matches_th:0.100_min-visib:-1.000.json
│   ├── scores_th:0.020_min-visib:-1.000.json
│   ├── scores_th:0.050_min-visib:-1.000.json
│   └── scores_th:0.100_min-visib:-1.000.json
├── error:mspd_ntop:-1
│   ├── errors_000001.json
│   ├── errors_000002.json
│   ├── errors_000003.json
│   ├── errors_000004.json
│   ├── errors_000005.json
│   ├── errors_000006.json
│   ├── errors_000007.json
│   ├── errors_000008.json
│   ├── errors_000009.json
│   ├── errors_000010.json
│   ├── errors_000011.json
│   ├── errors_000012.json
│   ├── errors_000013.json
│   ├── errors_000014.json
│   ├── errors_000015.json
│   ├── errors_000016.json
│   ├── errors_000017.json
│   ├── errors_000018.json
│   ├── errors_000019.json
│   ├── errors_000020.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:15.000_min-visib:-1.000.json
│   ├── matches_th:20.000_min-visib:-1.000.json
│   ├── matches_th:25.000_min-visib:-1.000.json
│   ├── matches_th:30.000_min-visib:-1.000.json
│   ├── matches_th:35.000_min-visib:-1.000.json
│   ├── matches_th:40.000_min-visib:-1.000.json
│   ├── matches_th:45.000_min-visib:-1.000.json
│   ├── matches_th:50.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:15.000_min-visib:-1.000.json
│   ├── scores_th:20.000_min-visib:-1.000.json
│   ├── scores_th:25.000_min-visib:-1.000.json
│   ├── scores_th:30.000_min-visib:-1.000.json
│   ├── scores_th:35.000_min-visib:-1.000.json
│   ├── scores_th:40.000_min-visib:-1.000.json
│   ├── scores_th:45.000_min-visib:-1.000.json
│   ├── scores_th:50.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
├── error:mssd_ntop:-1
│   ├── errors_000001.json
│   ├── errors_000002.json
│   ├── errors_000003.json
│   ├── errors_000004.json
│   ├── errors_000005.json
│   ├── errors_000006.json
│   ├── errors_000007.json
│   ├── errors_000008.json
│   ├── errors_000009.json
│   ├── errors_000010.json
│   ├── errors_000011.json
│   ├── errors_000012.json
│   ├── errors_000013.json
│   ├── errors_000014.json
│   ├── errors_000015.json
│   ├── errors_000016.json
│   ├── errors_000017.json
│   ├── errors_000018.json
│   ├── errors_000019.json
│   ├── errors_000020.json
│   ├── matches_th:0.050_min-visib:-1.000.json
│   ├── matches_th:0.100_min-visib:-1.000.json
│   ├── matches_th:0.150_min-visib:-1.000.json
│   ├── matches_th:0.200_min-visib:-1.000.json
│   ├── matches_th:0.250_min-visib:-1.000.json
│   ├── matches_th:0.300_min-visib:-1.000.json
│   ├── matches_th:0.350_min-visib:-1.000.json
│   ├── matches_th:0.400_min-visib:-1.000.json
│   ├── matches_th:0.450_min-visib:-1.000.json
│   ├── matches_th:0.500_min-visib:-1.000.json
│   ├── scores_th:0.050_min-visib:-1.000.json
│   ├── scores_th:0.100_min-visib:-1.000.json
│   ├── scores_th:0.150_min-visib:-1.000.json
│   ├── scores_th:0.200_min-visib:-1.000.json
│   ├── scores_th:0.250_min-visib:-1.000.json
│   ├── scores_th:0.300_min-visib:-1.000.json
│   ├── scores_th:0.350_min-visib:-1.000.json
│   ├── scores_th:0.400_min-visib:-1.000.json
│   ├── scores_th:0.450_min-visib:-1.000.json
│   └── scores_th:0.500_min-visib:-1.000.json
├── error:reS_ntop:-1
│   ├── errors_000001.json
│   ├── errors_000002.json
│   ├── errors_000003.json
│   ├── errors_000004.json
│   ├── errors_000005.json
│   ├── errors_000006.json
│   ├── errors_000007.json
│   ├── errors_000008.json
│   ├── errors_000009.json
│   ├── errors_000010.json
│   ├── errors_000011.json
│   ├── errors_000012.json
│   ├── errors_000013.json
│   ├── errors_000014.json
│   ├── errors_000015.json
│   ├── errors_000016.json
│   ├── errors_000017.json
│   ├── errors_000018.json
│   ├── errors_000019.json
│   ├── errors_000020.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:2.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:2.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
├── error:teS_ntop:-1
│   ├── errors_000001.json
│   ├── errors_000002.json
│   ├── errors_000003.json
│   ├── errors_000004.json
│   ├── errors_000005.json
│   ├── errors_000006.json
│   ├── errors_000007.json
│   ├── errors_000008.json
│   ├── errors_000009.json
│   ├── errors_000010.json
│   ├── errors_000011.json
│   ├── errors_000012.json
│   ├── errors_000013.json
│   ├── errors_000014.json
│   ├── errors_000015.json
│   ├── errors_000016.json
│   ├── errors_000017.json
│   ├── errors_000018.json
│   ├── errors_000019.json
│   ├── errors_000020.json
│   ├── matches_th:10.000_min-visib:-1.000.json
│   ├── matches_th:2.000_min-visib:-1.000.json
│   ├── matches_th:5.000_min-visib:-1.000.json
│   ├── scores_th:10.000_min-visib:-1.000.json
│   ├── scores_th:2.000_min-visib:-1.000.json
│   └── scores_th:5.000_min-visib:-1.000.json
└── log.log

5 directories, 159 files

```

**Comment by monajalal** [comment]
installing bop_renderer solves the issue https://github.com/shanice-l/gdrnpp_bop2022/issues/101#issuecomment-1875825306
